rojgar/address/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('load_state', LoadStateView.as_view(),name='load_state'),
    path('load_district', LoadDistrictView.as_view(),name='load_district'),
    path('load_municipality', LoadMunicipalityView.as_view(),name='load_municipality'),
    path('load_districts', LoadDistrictView1.as_view(), name='load_districts'),
]

rojgar/client/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('client_dashboard', ClientDashboardView.as_view(), name='client_dashboard'),
    path('register_client', RegisterClientView.as_view(), name='register_client'),

]

rojgar/employee/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('employee_dashboard', EmployeeDashboardView.as_view(), name='employee_dashboard'),
    path('register_employee', RegisterEmployeeView.as_view(), name='register_employee'),
    path('employee_service', EmployeeServiceView.as_view(), name='employee_service'),
    path('employee_bio', EmployeeBioView.as_view(), name='employee_bio'),
    path('employee_detail', EmployeeDetailView.as_view(), name='employee_detail'),
    path('update_employee', EmployeeUpdateView.as_view(), name='update_employee'),
    path('add_service', AddServiceView.as_view(), name='add_service'),
    path('add_bio', AddBioView.as_view(), name='add_bio'),
    path('update_profile', UpdateProfile.as_view(), name='update_profile'),
    path('add_profile', AddProfile.as_view(), name='add_profile'),

]

rojgar/job/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('manage-job/', ManageJobView.as_view(), name='manage_job'),
    path('manage-category/', ManageCategoryView.as_view(), name='manage_category'),
    path('create-job/', CreateJobView.as_view(), name='create_job'),
    path('create-category/', CreateCategoryView.as_view(), name='create_category'),
    path('update-job', UpdateJobView.as_view(), name='update_job'),
]

rojgar/rojgar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/job/', include(('job.urls','job'), namespace='job')),
    path('api/job/', include(('job.api_urls', 'job'), namespace='job_api')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('api/user/', include(('user.api_urls', 'user'), namespace='user_api')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('api/home/', include(('home.api_urls', 'home'), namespace='home_api')),
    path('employee/', include(('employee.urls', 'employee'), namespace='employee')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('address/', include(('address.urls', 'address'), namespace='address')),
    path('api/employee/', include(('employee.api_urls','employee'), namespace='employee_api')),
    path('servicerequest/', include(('servicerequest.urls', 'servicerequest'), namespace='servicerequest')),
    path('api/servicerequest/', include(('servicerequest.api_urls','servicerequest'), namespace='servicerequest_api')),

]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rojgar/user/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('logout',signout, name='logout'),
    path('customer-signup', CustomerSignUpView.as_view(), name='customer_signup'),
    path('employee-signup', EmployeeSignupView.as_view(), name='employee_signup'),

]

rojgar/client/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from address.models import *
from job.models import Job

# Create your models here.

class Client(models.Model):
    user = models.OneToOneField(User,related_name='user_client', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    state = models.ForeignKey(State, related_name='client_state', on_delete=models.CASCADE)
    district = models.ForeignKey(District, related_name='client_district', on_delete=models.CASCADE)
    municipality = models.ForeignKey(Municipality, related_name='client_municipality', on_delete=models.CASCADE)
    ward_number = models.IntegerField()
    street = models.CharField(max_length=100)
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return f'{self.full_name}'

rojgar/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='user_photo')
    photo = models.FileField(upload_to='media', blank=True,null=True)

rojgar/user/api/views.py
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework import status
from user.models import *
from ..serializers import *
import json
from rest_framework.parsers import FileUploadParser,MultiPartParser,JSONParser,FormParser

class CreateUserAPIView(APIView):

    def post(self, request):
        data = request.data
        print(data)
        serializer = UserSerializer(data = data)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Saved."})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CreateUserProfileAPIView(APIView):

    parser_classes = (MultiPartParser, FormParser)
    def post(self, request):
        data = request.data
        print(data)
        serializer = UserProfileSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Saved."})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ListUserAPIView(ListAPIView):

    serializer_class = User
    queryset = User.objects.all()


class ListUserProfileAPIView(ListAPIView):

    serializer_class = UserProfileSerializer
    queryset = UserProfile.objects.all()


class GetUserProfileAPIView(APIView):

    def get(self, request):
        user_id = request.GET['user_id']
        user_profile = UserProfile.objects.get(user_id=user_id)
        data = {'image': user_profile.photo.url }
        return Response(data)


class UpdateUserProfileAPIView(APIView):

    parser_classes = (MultiPartParser, FormParser)
    def put(self, request):
        data = request.data
        id = request['user_id']
        user_profile = UserProfile.objects.get(user_id=id)
        serializer = UserProfileSerializer(instance=user_profile, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Updated."})
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)


class UpdateUserAPIView(APIView):

    def put(self, request):
        data = request.data
        id = request['id']
        user = User.objects.get(id=id)
        serializer = UserSerializer(instance=user, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Updated."})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

rojgar/user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from django.contrib.auth.models import Group, User
from django.contrib.auth import login, authenticate, logout
import json
# Create your views here.

def hasGroup(user, groupName):
    group = Group.objects.get(name=groupName)
    return True if group in user.groups.all() else False


class CustomerSignUpView(View):

    def get(self, request):
        return render(request, 'user/customer_signup_form.html')

class EmployeeSignupView(View):

    def get(self, request):
        return render(request, 'user/employee_signup_form.html')

class Login(View):

    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        data = request.body.decode('UTF-8')
        user_data = json.loads(data)
        user_name = user_data.get('userName')
        password = user_data.get('password')
        authenticated_user = authenticate(username=user_name, password=password)
        if authenticated_user is not None:
            login(request, authenticated_user)
            if next:
                if hasGroup(request.user, 'employee'):
                    return JsonResponse({"response":"http://127.0.0.1:4000/employee/employee_dashboard"})

                elif hasGroup(request.user, 'client'):
                    return JsonResponse({"response": 'http://127.0.0.1:4000/client/client_dashboard'})

                elif hasGroup(request.user, 'admin'):
                   return JsonResponse({"response":"http://127.0.0.1:4000/dashboard/admin"})

        else:
            return JsonResponse({"response": "UserName or Password is incorrect !"})


def dashbaord(request):
    if hasGroup(request.user, 'employee'):
        print(request.user)
        return render(request, 'employee/employee_dashboard.html')

    elif hasGroup(request.user, 'client'):
        return render(request, 'client/client_dashboard.html')

    elif hasGroup(request.user, 'admin'):
        return render(request, 'dashboard/admin_dashboard.html')


def signout(request):
    logout(request)
    return redirect('home:home')

rojgar/user/templates/user/customer_signup_form.html
{% extends 'home/base.html' %}
{% load static %}
<title> {% block title %} {{block.super}} :: Client Signup {% endblock %} </title>

{% block content %}
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<link rel="stylesheet" href="{% static 'user/css/validation.css' %}">
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign Up for Client</h5>
                    <hr class="my-4">
                    <form class="form-signup" id="client_signup_form" data-s-url="{% url 'address:load_state' %}"
                          data-d-url="{% url 'address:load_district' %}"
                          data-m-url="{% url 'address:load_municipality' %}"
                          data-post-url="{% url 'client:register_client' %}"
                          data-bind="submit: save"
                    >

                        <div class="form-group">
                            <label>Full Name *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user"></i></span>
                                </div>


                                <input type="text" data-bind="value: fullName" name="full_name" placeholder="Full Name "
                                       id="id_full_name" class="form-control"
                                       required="true" maxlength="30">
                                <div class="id_full_name_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>User Name *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user"></i></span>
                                </div>

                                <input type="text" name="username" data-bind="value: userName" placeholder="Username"
                                       class="form-control" required="" id="id_username" maxlength="150">
                                <div class="id_username_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Mobile Number *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone-number"></i></span>
                                </div>

                                <input type="text" data-bind="value: mobileNumber" name="mobile_number"
                                       placeholder="Mobile Number " id="id_phone_number" class="form-control"
                                       required="true" maxlength="10">
                                <div class="id_phone_number_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Email *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                                </div>
                                <input type="email" name="email" data-bind="value: email" placeholder="E-Mail"
                                       class="form-control" required="true" id="id_email" maxlength="254">
                                <div class="id_email_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Address </label>
                            <br>
                            <!--                         <div class="col-sm-12 col-md-12 col-lg-15 mx-auto">-->
                            <label>State *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i></span>
                                </div>
                                <select name="state" class="form-control" data-bind="options: stateList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedState,
                                 optionsCaption: 'Choose State...' "></select>

                            </div>

                            <label>District *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i></span>
                                </div>
                                <select name="district" class="form-control" data-bind="options: districtList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedDistrict,
                                 optionsCaption: 'Choose District...' "></select>

                            </div>

                            <label>Municipality *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i></span>
                                </div>

                                <select name="municipality" class="form-control" data-bind="options: municipalityList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedMunicipality,
                                 optionsCaption: 'Choose Municipality...' "></select>
                            </div>
                            <label>Ward Number *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i> </span>
                                </div>
                                <input name="wardno" type="number" min="1" data-bind="value: wardNumber" name="wardno"
                                       class="form-control" placeholder="Ward Number"/>
                            </div>
                            <label>Street *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i> </span>
                                </div>
                                <input name="street" type="text" data-bind="value: street" name="street"
                                       class="form-control" placeholder="Street"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Password *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-lock"></i></span>
                                </div>

                                <input name="password" id="password" type="password" data-bind="value: password"
                                       placeholder="Password" class="form-control" required="" id="id_password1">
                                <div class="id_password1_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Confirm Password *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-lock"></i></span>
                                </div>

                                <input type="password" name="cpassword" placeholder="Confirm Password"
                                       class="form-control" required="" id="id_password2">
                                <div class="id_password2_error"></div>
                            </div>
                        </div>

                        <br>

                        <!--<div class="more-option terms">-->
                            <!--<div class="form-check">-->
                                <!--<input class="form-check-input" type="checkbox" value id="candidate-agree">-->
                                <!--<label class="form-check-label" for="defaultCheck2">-->
                                    <!--I accept the <a href="/pages/terms-and-conditions/">terms &amp; conditions</a>-->
                                <!--</label>-->
                            <!--</div>-->
                        <!--</div>-->
                        <br>
                        <button type="submit" style="background-color:#435df8;"
                                class="btn btn-md button primary-bg btn-block">Register
                        </button>
                        <button type="button" style="background-color:#dc3545;"
                                class="btn btn-md button info-bg btn-block" data-dismiss="modal">Cancel
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="{% static 'user/js/validation.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'client/js/client.js' %}"></script>
{% endblock %}

rojgar/user/templates/user/employee_signup_form.html
{% extends 'home/base.html' %}
{% load static %}
<title> {% block title %} {{block.super}} :: Employee Signup {% endblock %} </title>

{% block content %}
<link rel="stylesheet" href="{% static 'user/css/validation.css' %}">
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign Up for Employee</h5>
                    <hr class="my-4">
                    <form class="form-signup" id="employee_signup_form" data-s-url="{% url 'address:load_state' %}"
                          data-d-url="{% url 'address:load_district' %}"
                          data-m-url="{% url 'address:load_municipality' %}"
                          data-post-url="{% url 'employee:register_employee' %}"
                          data-bind="submit: save"
                    >

                        <div class="form-group">
                            <label>Full Name *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user"></i></span>
                                </div>


                                <input type="text" data-bind="value: fullName" name="full_name" placeholder="Full Name "
                                       id="id_full_name" class="form-control"
                                       required="true" maxlength="30">
                                <div class="id_full_name_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>User Name *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user"></i></span>
                                </div>

                                <input type="text" name="username" data-bind="value: userName" placeholder="Username"
                                       class="form-control" required="" id="id_username" maxlength="150">
                                <div class="id_username_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Mobile Number *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone-number"></i></span>
                                </div>

                                <input type="text" data-bind="value: mobileNumber" name="mobile_number"
                                       placeholder="Mobile Number " id="id_phone_number" class="form-control"
                                       required="true" maxlength="10">
                                <div class="id_phone_number_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Email *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                                </div>
                                <input type="email" name="email" data-bind="value: email" placeholder="E-Mail"
                                       class="form-control" required="true" id="id_email" maxlength="254">
                                <div class="id_email_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Address </label>
                            <br>
                            <!--                         <div class="col-sm-12 col-md-12 col-lg-15 mx-auto">-->
                            <label>State *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i></span>
                                </div>
                                <select name="state" class="form-control" data-bind="options: stateList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedState,
                                 optionsCaption: 'Choose State...' "></select>

                            </div>

                            <label>District *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i></span>
                                </div>
                                <select name="district" class="form-control" data-bind="options: districtList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedDistrict,
                                 optionsCaption: 'Choose District...' "></select>

                            </div>

                            <label>Municipality *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i></span>
                                </div>

                                <select name="municipality" class="form-control" data-bind="options: municipalityList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedMunicipality,
                                 optionsCaption: 'Choose Municipality...' "></select>
                            </div>
                            <label>Ward Number *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i> </span>
                                </div>
                                <input name="wardno" type="number" min="1" data-bind="value: wardNumber" name="wardno"
                                       class="form-control" placeholder="Ward Number"/>
                            </div>
                            <label>Street *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa-map-marker"></i> </span>
                                </div>
                                <input name="street" type="text" data-bind="value: street" name="street"
                                       class="form-control" placeholder="Street"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Password *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-lock"></i></span>
                                </div>

                                <input name="password" id="password" type="password" data-bind="value: password"
                                       placeholder="Password" class="form-control" required="" id="id_password1">
                                <div class="id_password1_error"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Confirm Password *</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-lock"></i></span>
                                </div>

                                <input type="password" name="cpassword" placeholder="Confirm Password"
                                       class="form-control" required="" id="id_password2">
                                <div class="id_password2_error"></div>
                            </div>
                        </div>


                        <br>

                        <!--<div class="more-option terms">-->
                            <!--<div class="form-check">-->
                                <!--<input class="form-check-input" type="checkbox" value id="candidate-agree">-->
                                <!--<label class="form-check-label" for="defaultCheck2">-->
                                    <!--I accept the <a href="/pages/terms-and-conditions/">terms &amp; conditions</a>-->
                                <!--</label>-->
                            <!--</div>-->
                        <!--</div>-->
                        <br>
                        <button type="submit" style="background-color:#435df8;"
                                class="btn btn-md button primary-bg btn-block">Register
                        </button>
                        <button type="button" style="background-color:#dc3545;"
                                class="btn btn-md button info-bg btn-block" data-dismiss="modal">Cancel
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="{% static 'user/js/employee_form_validation.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/employee_address.js' %}"></script>
{% endblock %}

rojgar/user/templates/user/signup_page.html
{% extends 'home/base.html' %}

<div class="container">

    <center>
        <h3>Sign Up</h3>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#">As Customer</a></li>
            <li><a href="#">As Employee</a></li>
        </ul>
    </center>

</div>