rojgar/address/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('load_state', LoadStateView.as_view(),name='load_state'),
    path('load_district', LoadDistrictView.as_view(),name='load_district'),
    path('load_municipality', LoadMunicipalityView.as_view(),name='load_municipality'),
    path('load_districts', LoadDistrictView1.as_view(), name='load_districts'),
]

rojgar/employee/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('employee_dashboard', EmployeeDashboardView.as_view(), name='employee_dashboard'),
    path('register_employee', RegisterEmployeeView.as_view(), name='register_employee'),
    path('employee_service', EmployeeServiceView.as_view(), name='employee_service'),
    path('employee_bio', EmployeeBioView.as_view(), name='employee_bio'),
    path('employee_detail', EmployeeDetailView.as_view(), name='employee_detail'),
    path('update_employee', EmployeeUpdateView.as_view(), name='update_employee'),
    path('add_service', AddServiceView.as_view(), name='add_service'),
    path('add_bio', AddBioView.as_view(), name='add_bio'),
    path('update_profile', UpdateProfile.as_view(), name='update_profile'),
    path('add_profile', AddProfile.as_view(), name='add_profile'),

]

rojgar/home/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('service', ServiceView.as_view(), name='service'),
    path('contact', ContactView.as_view(), name='contact'),
    path('employee', ServiceEmployee.as_view(), name='employee'),
    path('employee_detail', EmployeeDetail.as_view(), name='employee_detail'),
    path('employees', Employee.as_view(), name='employees'),
]

rojgar/job/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('manage-job/', ManageJobView.as_view(), name='manage_job'),
    path('manage-category/', ManageCategoryView.as_view(), name='manage_category'),
    path('create-job/', CreateJobView.as_view(), name='create_job'),
    path('create-category/', CreateCategoryView.as_view(), name='create_category'),
    path('update-job', UpdateJobView.as_view(), name='update_job'),
]

rojgar/rojgar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/job/', include(('job.urls','job'), namespace='job')),
    path('api/job/', include(('job.api_urls', 'job'), namespace='job_api')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('api/user/', include(('user.api_urls', 'user'), namespace='user_api')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('api/home/', include(('home.api_urls', 'home'), namespace='home_api')),
    path('employee/', include(('employee.urls', 'employee'), namespace='employee')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('address/', include(('address.urls', 'address'), namespace='address')),
    path('api/employee/', include(('employee.api_urls','employee'), namespace='employee_api')),
    path('servicerequest/', include(('servicerequest.urls', 'servicerequest'), namespace='servicerequest')),
    path('api/servicerequest/', include(('servicerequest.api_urls','servicerequest'), namespace='servicerequest_api')),

]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rojgar/user/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('logout',signout, name='logout'),
    path('customer-signup', CustomerSignUpView.as_view(), name='customer_signup'),
    path('employee-signup', EmployeeSignupView.as_view(), name='employee_signup'),

]

rojgar/employee/models.py
from django.db import models
from django.contrib.auth.models import User
from address.models import *
from job.models import Job

# Create your models here.
class Employee(models.Model):
    user = models.OneToOneField(User,related_name='user_emp', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    state = models.ForeignKey(State, related_name='employee_state', on_delete=models.CASCADE)
    district = models.ForeignKey(District, related_name='employee_district', on_delete=models.CASCADE)
    municipality = models.ForeignKey(Municipality, related_name='employee_municipality', on_delete=models.CASCADE)
    ward_number = models.IntegerField()
    street = models.CharField(max_length=100)
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField()


    def __str__(self):
        return f'{self.full_name}'


class EmployeeSkill(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_skill', on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.employee} | {self.skill}'


class EmployeeJob(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_job', on_delete=models.CASCADE)
    job = models.ForeignKey(Job, related_name='emp_job', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.employee}|{self.job}'


class EmployeeHistory(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_history', on_delete=models.CASCADE)
    task = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    description = models.TextField()


class EmployeeBio(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_bio', on_delete=models.CASCADE)
    education = models.TextField()
    experience = models.TextField()
    others = models.TextField()


    def __str__(self):
        return f'{self.employee}|{self.education}'

rojgar/home/models.py
from django.db import models

# Create your models here.

rojgar/employee/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.models import Group, User
from django.contrib.auth import login, authenticate
from .models import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
from home.decorators import group_required
from rest_framework.views import APIView
# Create your views here.

@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeDashboardView(View):
    def get(self, request):
        return render(request, 'employee/employee_dashboard.html')


class RegisterEmployeeView(View):



    def post(self, request):
        data = request.body.decode('UTF-8')
        emp_data = json.loads(data)
        print(emp_data)
        user_name = emp_data.get('userName')
        password1 = emp_data.get('password')
        # password2 = emp_data.get('password2')
        full_name = emp_data.get('fullName')
        mobile_number = emp_data.get('mobileNumber')
        email = emp_data.get('email')
        state = emp_data.get('state')
        district = emp_data.get('district')
        municipality = emp_data.get('municipality')
        ward_number = emp_data.get('wardNumber')
        street = emp_data.get('street')
        if full_name != None:

            user = User.objects.create_user(username=user_name,password=password1)
            employee = Employee(full_name=full_name, mobile_number=mobile_number,
                                email=email, state_id=state, district_id=district, municipality_id=municipality,
                                ward_number=ward_number, street=street)
            employee.user = user
            group = Group.objects.get(name='employee')
            group.user_set.add(user)
            group.save()
            employee.save()

            authenticated_user = authenticate(username=user_name, password=password1)
            login(request, authenticated_user)
            if next:
                return JsonResponse({"response": "http://127.0.0.1:4000/employee/employee_dashboard"})
            return redirect('home:home')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeServiceView(View):

    def get(self, request):
        return render(request,'employee/employee_service.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeBioView(View):

    def get(self, request):
        return render(request, 'employee/employee_bio.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeDetailView(View):

    def get(self, request):
        return render(request, 'employee/employee_detail.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeUpdateView(View):

    def get(self, request):
        return render(request, 'employee/update_employee.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class AddServiceView(View):

    def get(self, request):
        return render(request, 'employee/add_service.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class AddBioView(View):

    def get(self, request):
        return render(request, 'employee/add_bio.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class UpdateProfile(View):

    def get(self, request):
        return render(request, 'employee/update_profile.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class AddProfile(View):

    def get(self, request):
        return render(request, 'employee/add_profile.html')

rojgar/home/views.py
from django.shortcuts import render
from django.views import View


# Create your views here.

class Home(View):

    def get(self, request):
        return render(request, 'home/home.html')


class ServiceView(View):

    def get(self, request):
        return render(request, 'home/service.html')


class ContactView(View):

    def get(self, request):
        return render(request, 'home/contact.html')


class ServiceEmployee(View):

    def get(self, request):
        return render(request, 'home/employee.html')


class Employee(View):

    def get(self, request):
        return render(request, 'home/employees.html')


class EmployeeDetail(View):

    def get(self, request):
        return render(request, 'home/employee_detail.html')

rojgar/home/templates/home/_body.html
<div class="container">
    <h4 class="bg-info text-white m-2 p-2">About Us</h4>
    <p class="m-2">"Rojgar Application" is a web-based application. It provides a platform to employee to work through
        it and client (i.e. person who needs service.) to find out employee. It acts as an inter-mediatory role between
        employee and client.</p>


</div>
<div class="container">
    <p class="m-2">
        Rojgar Application provides a digital platform for everyone who wants to work and earn money. It includes various
        major categories and sub categories such as Information and Technology, Teacher, Farmer, Repair, design, cleaning,
        rituals, event, travel and tours, vehicles hire, delivery, technicians, medical and multi skilled professionals are
        the major categories. 
    </p>
</div>

rojgar/home/templates/home/_navbar.html
<nav class="navbar navbar-expand-md rojgar-navbar sticky-top">
    <!-- Brand -->
    <a class="navbar-brand" href="#">Rojgar</a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:service' %}">Service</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item"> <a class="nav-link bg-primary text-white"
                                     href="{% url 'user:logout' %}" > Logout</a>
            </li>
            {% else %}
           <li class="nav-item"> <a class="nav-link bg-primary text-white" data-toggle="modal" data-target="#myModal"
                                     href="#" > Login</a>
             </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle bg-info" href="#" id="navbardrop" data-toggle="dropdown">
                    Sign Up
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item text-dark" href="{% url 'user:employee_signup' %}">As Employee</a>
                    <a class="dropdown-item text-dark" href="{% url 'user:customer_signup' %}">As Client</a>

                </div>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

<script>
    $(document).on('click', 'ul li', function(){
        $(this).addClass('active').siblings().removeClass('active');
    });

</script>

rojgar/home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Rojgar {% endblock %}</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
    <!-- font link -->
    <link href='https://fonts.googleapis.com/css?family=Alice' rel='stylesheet'>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"></script>


    <style>
        body {
            font-family: 'Alice';font-size: 20px;
        }
    </style>

</head>
<body>
{% include 'home/_navbar.html' %}
{% include 'user/login.html' %}
<script src="{% static 'user/js/login.js' %}"></script>
{% block content %}

{% endblock %}

</body>
</html>

rojgar/home/templates/home/contact.html
{% extends 'home/base.html' %}
<title> {% block title %} {{block.super}} :: Contact Us {% endblock %} </title>

{% block content %}
<a class="form-area">
    <div class="col-sm-8 col-md-7 col-lg-5 mx-auto">
        <br>
        <h3>Contact Us</h3>
        <p> Any questions?? you can contact us from below form.</p>
        <form role="form" method="post">

            <div class="form-group">
                <label>Name *</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name" maxlength="70"
                       required>
            </div>
            <div class="form-group">
                <label>Email *</label>
                <input type="text" class="form-control" id="email" name="email" placeholder="Email" required>
            </div>

            <div class="form-group">
                <label>Subject *</label>
                <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" maxlength="70"
                       required>
            </div>
            <div class="form-group">
                <label>Message *</label>
                <textarea class="form-control" type="textarea" id="message" placeholder="Message" maxlength="300"
                          rows="7"></textarea>
            </div>
            <br>
            <button class="btn btn-md btn-success float float-right">Submit</button>

            <!--        <button type="button" id="submit" name="submit" class="btn btn-m btn-secondary">Submit Form</button>-->
        </form>
    </div>
    </div>
</a>
{% endblock %}

rojgar/home/templates/home/employee.html
{% extends 'home/base.html' %}
{% load static %}
<title>{% block title %}{{block.super}} :: Employee{% endblock %}</title>
{% block content %}
<link rel="stylesheet" href="{% static 'home/css/service.css' %}"/>

<!-- ko if: employeeService().length<1 -->
<div data-bind="" class="jumbotron mt-2">
  <div class="container">
    <h4>Sorry, Employees are not found !</h4>
  </div>
</div>
<!-- /ko -->
<div class="container">
    <div class="row">
        <!-- ko foreach: employeeService -->
        <div class="col-md-2 bg-light rojgar-service">
            <img class=" mx-auto d-block job-img" width="100px" height="100px" data-bind="attr: { src: emp_photo } "/>
            <p data-bind="text: emp_name"></p>
            <p data-bind="text: emp_mobile_number"></p>
            <a class="btn btn-info" data-bind="click: $root.loadEmployeeDetail" href="#">Detail</a>
            {% if user.is_authenticated %}
            <a class="btn btn-primary" data-bind="click: $root.requestEmployee" href="#">Request</a>
            {% endif %}
        </div>
        <!-- /ko -->
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'home/js/employee_service.js' %}"></script>
{% endblock %}

rojgar/home/templates/home/employee_detail.html
{% extends 'home/base.html' %}
{% load static %}
<title>{% block title %}{{ block.super }}::Employee-Detail{% endblock %}</title>
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md mt-3">
            <p class="text-white bg-info p-2">Employee Detail</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <p><b>Name:</b> <i data-bind="text: name"></i></p>
            <p><b>Address:</b> <i data-bind="text: address"></i></p>
            <p><b>Mobile Number:</b> <i data-bind="text: mobile_no"></i></p>
            <p><b>Email:</b> <i data-bind="text: email"></i></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <h5 class="bg-info text-white p-2">Employee Bio</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <p><b>Education:</b></p>
            <p><b>Experience: </b></p>
            <p><b>Other's Skill:</b></p>
        </div>
        <div class="col-md-6">
            <p><i data-bind="text: education"></i></p>
            <p><i data-bind="text: experience"></i></p>
            <p><i data-bind="text: other"></i></p>
        </div>
    </div>

</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'home/js/employee_detail.js' %}"></script>

{% endblock %}

rojgar/home/templates/home/employees.html
{% extends 'home/base.html' %}
{% load static %}
<title>{% block title %}{{block.super}} :: Employee{% endblock %}</title>
{% block content %}
<link rel="stylesheet" href="{% static 'home/css/service.css' %}"/>
<div class="container">
    <div class="row">
        <!-- ko foreach: employee -->
        <div class="col-md-2 bg-light rojgar-service">
            <img class=" mx-auto d-block job-img" width="100px" height="100px" src=""/>
            <p data-bind="text: name"></p>
            <p data-bind="text: mobile_number"></p>
            <a class="btn btn-info" data-bind="click: $root.loadEmployeeDetail" href="#">Detail</a>
            <a class="btn btn-primary" href="#">Request</a>
        </div>
        <!-- /ko -->
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'home/js/service.js' %}"></script>
{% endblock %}

rojgar/home/templates/home/footer.html
<!-- Footer -->
<footer class="container-fluid m-0"  style="background-color:#382e38;">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0">

        <ul class="list-unstyled">
          <li>
            <a  href="{% url 'home:home' %}" style="color:white;">Home</a>
          </li>
           <li>
            <a href="{% url 'home:service' %}"style="color:white;">Services</a>
          </li>
          <li>
            <a href="{% url 'home:contact' %}"style="color:white;">Contact Us</a>
          </li>

        </ul>

      </div>
      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
        <ul class="list-unstyled">
          <li>
            <a href=""style="color:white;">Login</a>
          </li>
          <li>
            <a href="" style="color:white;">Sign Up</a>
          </li>
        </ul>

      </div>
       <div class="col-md-3 mb-md-0 mb-3">
        <ul class="list-unstyled">
          <li>
            <a href=""style="color:white;">FAQ</a>
          </li>
          <li>
            <a href="" style="color:white;">Privacy Policy</a>
          </li>
           <li>
            <a href="" style="color:white;">Terms of Services</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"style="color:white;">© 2019
    <a href=""style="color:white;"> Rojgar.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

rojgar/home/templates/home/home.html
{% extends 'home/base.html' %}
<title>{% block title %} {{block.super}}:: Home{% endblock %}</title>
{% block content %}
{% include 'home/_body.html' %}
{% endblock %}

rojgar/home/templates/home/service.html
{% extends 'home/base.html' %}
{% load static %}
<title>{% block title %}{{block.super}} :: Service{% endblock %}</title>
{% block content %}
<link rel="stylesheet" href="{% static 'home/css/service.css' %}"/>
<div class="container">
    <div class="row">
        <div class="col-md mt-2">
            <h5 class="text-white bg-info p-2">List of Services</h5>
        </div>

    </div>
    <div class="row">
        <div class="col-md">
            <form id="search_employee"
            data-d-url="{% url 'address:load_districts' %}">
                <b>Search:</b>
                <select data-bind="options: $root.serviceList,
                                                           optionsText: 'name',
                                                           optionsValue: 'id',
                                                           value: selectedService,
                                                           optionsCaption: 'Choose Service...'">
                    </select>
                <select  data-bind="options: districtList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedDistrict,
                                 optionsCaption: 'Choose District...' ">

                </select>


                <a class="btn btn-success" data-bind="click: search" href="#">Search</a>
            </form>


        </div>
    </div>
</div>


<div class="container mt-2" data-bind="template: { name: 'service_template', foreach: service }">

</div>

<script type="text/html" id="service_template">
<div class="row">
   <div class="col-md-2">
    <h5 class="bg-info text-white p-2" data-bind="text: name"></h5>
   </div>

</div>
<div class="row">
<!-- ko foreach: job_list -->
    <!-- ko template: 'job_template' -->
    <!-- /ko -->
<!-- /ko -->
</div>

<!-- ko foreach: category_list -->
    <!-- ko template: 'service_template' -->
    <!-- /ko -->
<!-- /ko -->

</script>

<script type="text/html" id="job_template">
        <div class="col-md-2 bg-light rojgar-service">
            <img class=" mx-auto d-block job-img" width="100px" height="100px" data-bind="attr: { src: image }"/>
            <a class="text-info" href="#"  data-bind="text: name, click: $root.loadEmployee"></a>
        </div>

</script>


<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'home/js/service.js' %}"></script>


{% endblock %}