rojgar/address/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('load_state', LoadStateView.as_view(),name='load_state'),
    path('load_district', LoadDistrictView.as_view(),name='load_district'),
    path('load_municipality', LoadMunicipalityView.as_view(),name='load_municipality'),
    path('load_districts', LoadDistrictView1.as_view(), name='load_districts'),
]

rojgar/employee/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('employee_dashboard', EmployeeDashboardView.as_view(), name='employee_dashboard'),
    path('register_employee', RegisterEmployeeView.as_view(), name='register_employee'),
    path('employee_service', EmployeeServiceView.as_view(), name='employee_service'),
    path('employee_bio', EmployeeBioView.as_view(), name='employee_bio'),
    path('employee_detail', EmployeeDetailView.as_view(), name='employee_detail'),
    path('update_employee', EmployeeUpdateView.as_view(), name='update_employee'),
    path('add_service', AddServiceView.as_view(), name='add_service'),
    path('add_bio', AddBioView.as_view(), name='add_bio'),
    path('update_profile', UpdateProfile.as_view(), name='update_profile'),
    path('add_profile', AddProfile.as_view(), name='add_profile'),

]

rojgar/job/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('manage-job/', ManageJobView.as_view(), name='manage_job'),
    path('manage-category/', ManageCategoryView.as_view(), name='manage_category'),
    path('create-job/', CreateJobView.as_view(), name='create_job'),
    path('create-category/', CreateCategoryView.as_view(), name='create_category'),
    path('update-job', UpdateJobView.as_view(), name='update_job'),
]

rojgar/rojgar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/job/', include(('job.urls','job'), namespace='job')),
    path('api/job/', include(('job.api_urls', 'job'), namespace='job_api')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('api/user/', include(('user.api_urls', 'user'), namespace='user_api')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('api/home/', include(('home.api_urls', 'home'), namespace='home_api')),
    path('employee/', include(('employee.urls', 'employee'), namespace='employee')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('address/', include(('address.urls', 'address'), namespace='address')),
    path('api/employee/', include(('employee.api_urls','employee'), namespace='employee_api')),
    path('servicerequest/', include(('servicerequest.urls', 'servicerequest'), namespace='servicerequest')),
    path('api/servicerequest/', include(('servicerequest.api_urls','servicerequest'), namespace='servicerequest_api')),

]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rojgar/servicerequest/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('create_service_request', CreateServiceRequest.as_view(), name='create_service_request'),
    path('employee_list_service_request', EmployeeServiceRequestList.as_view(), name='employee_list_service_request'),
    path('client_list_service_request', ClientServiceRequestList.as_view(), name='client_list_service_request'),

]

rojgar/employee/models.py
from django.db import models
from django.contrib.auth.models import User
from address.models import *
from job.models import Job

# Create your models here.
class Employee(models.Model):
    user = models.OneToOneField(User,related_name='user_emp', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    state = models.ForeignKey(State, related_name='employee_state', on_delete=models.CASCADE)
    district = models.ForeignKey(District, related_name='employee_district', on_delete=models.CASCADE)
    municipality = models.ForeignKey(Municipality, related_name='employee_municipality', on_delete=models.CASCADE)
    ward_number = models.IntegerField()
    street = models.CharField(max_length=100)
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField()


    def __str__(self):
        return f'{self.full_name}'


class EmployeeSkill(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_skill', on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.employee} | {self.skill}'


class EmployeeJob(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_job', on_delete=models.CASCADE)
    job = models.ForeignKey(Job, related_name='emp_job', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.employee}|{self.job}'


class EmployeeHistory(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_history', on_delete=models.CASCADE)
    task = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    description = models.TextField()


class EmployeeBio(models.Model):
    employee = models.ForeignKey(Employee, related_name='employee_bio', on_delete=models.CASCADE)
    education = models.TextField()
    experience = models.TextField()
    others = models.TextField()


    def __str__(self):
        return f'{self.employee}|{self.education}'

rojgar/employee/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.models import Group, User
from django.contrib.auth import login, authenticate
from .models import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
from home.decorators import group_required
from rest_framework.views import APIView
# Create your views here.

@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeDashboardView(View):
    def get(self, request):
        return render(request, 'employee/employee_dashboard.html')


class RegisterEmployeeView(View):



    def post(self, request):
        data = request.body.decode('UTF-8')
        emp_data = json.loads(data)
        print(emp_data)
        user_name = emp_data.get('userName')
        password1 = emp_data.get('password')
        # password2 = emp_data.get('password2')
        full_name = emp_data.get('fullName')
        mobile_number = emp_data.get('mobileNumber')
        email = emp_data.get('email')
        state = emp_data.get('state')
        district = emp_data.get('district')
        municipality = emp_data.get('municipality')
        ward_number = emp_data.get('wardNumber')
        street = emp_data.get('street')
        if full_name != None:

            user = User.objects.create_user(username=user_name,password=password1)
            employee = Employee(full_name=full_name, mobile_number=mobile_number,
                                email=email, state_id=state, district_id=district, municipality_id=municipality,
                                ward_number=ward_number, street=street)
            employee.user = user
            group = Group.objects.get(name='employee')
            group.user_set.add(user)
            group.save()
            employee.save()

            authenticated_user = authenticate(username=user_name, password=password1)
            login(request, authenticated_user)
            if next:
                return JsonResponse({"response": "http://127.0.0.1:4000/employee/employee_dashboard"})
            return redirect('home:home')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeServiceView(View):

    def get(self, request):
        return render(request,'employee/employee_service.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeBioView(View):

    def get(self, request):
        return render(request, 'employee/employee_bio.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeDetailView(View):

    def get(self, request):
        return render(request, 'employee/employee_detail.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class EmployeeUpdateView(View):

    def get(self, request):
        return render(request, 'employee/update_employee.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class AddServiceView(View):

    def get(self, request):
        return render(request, 'employee/add_service.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class AddBioView(View):

    def get(self, request):
        return render(request, 'employee/add_bio.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class UpdateProfile(View):

    def get(self, request):
        return render(request, 'employee/update_profile.html')


@method_decorator([login_required(login_url='home:home'), group_required('employee')],name='dispatch')
class AddProfile(View):

    def get(self, request):
        return render(request, 'employee/add_profile.html')

rojgar/employee/templates/employee/add_bio.html
{% extends 'employee/employee_dashboard.html' %}
{%load static %}
{% block employee %}
<div>
    <div class="col-md-6 m-2">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <!-- ko ifnot: education() -->
                <h4 class="modal-title">Add Bio</h4>
                <!-- /ko -->
                <h4 class="modal-title">Update Bio</h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label>Education</label>
                        <textarea  data-bind="value: education" class="form-control" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Experience</label>
                        <textarea data-bind="value: experience" class="form-control" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Other Skill</label>
                         <textarea data-bind="value: other" class="form-control" rows="5"></textarea>
                    </div>
                </form>
            </div>
            <input type="hidden" id="empID" value="{{ user.user_emp.id }}"/>
            <!-- Modal footer -->
            <div class="modal-footer">
                <!-- ko ifnot: education() -->
                <button class="btn btn-success" data-bind="click: save">Save</button>
                <!-- /ko -->
                <button class="btn btn-success" data-bind="click: save">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/add_bio.js' %}"></script>
{% endblock %}

rojgar/employee/templates/employee/add_profile.html
{% extends 'employee/employee_dashboard.html' %}
{%load static %}
{% block employee %}
<div>
    <div class="col-md-6 m-2">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">

                <h4 class="modal-title">Add Profile</h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form id="update-profile-form">
                    <input type="hidden"  id="user" value="{{ user.id }}">
                    <div class="form-group">
                        <label>Profile</label>
                        <input  id="image" type="file"  class="form-control" >
                    </div>
                </form>
            </div>
            <input type="hidden" id="empID" value="{{ user.user_emp.id }}"/>
            <!-- Modal footer -->
            <div class="modal-footer">

                <button class="btn btn-success" data-bind="click: save">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/add_profile.js' %}"></script>
{% endblock %}

rojgar/employee/templates/employee/add_service.html
{% extends 'employee/employee_dashboard.html' %}
{%load static %}
{% block employee %}
<div>
    <div class="col-md-6 m-2">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add Service</h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Service</span>
                        </div>
                        <select id= "emp_service" class="form-control" data-bind="options: $root.serviceList,
                                                           optionsText: 'name',
                                                           optionsValue: 'id',
                                                           value: service,
                                                           optionsCaption: 'Choose Service...'">
                    </select>
                    </div>

                </form>
            </div>
            <input type="hidden" id="empID" value="{{ user.user_emp.id }}"/>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button class="btn btn-success" data-bind="click: save">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/add_service.js' %}"></script>
{% endblock %}

rojgar/employee/templates/employee/employee_bio.html
{% extends 'employee/employee_dashboard.html' %}
{% load static %}
{% block employee %}
<input type="hidden"  id="empId" value="{{ user.user_emp.id }}">
<!-- ko ifnot: education() -->
<div>
    <a class="btn btn-success m-2" href="{% url 'employee:add_bio' %}">
        Add Bio
    </a>

</div>
<!-- /ko -->
<!-- ko if: education() -->
<div>
    <a class="btn btn-success m-2" href="{% url 'employee:add_bio' %}">
        Update Bio
    </a>

</div>
<!-- /ko -->

<div class="container">
    <div class="row border">
        <div class="col-md-3">
            <p><b>Education: </b></p>
            <p><b>Experience: </b></p>
            <p><b>Others: </b></p>
        </div>
        <div class="col-md-6">
            <p><i data-bind="text: education"></i></p>
            <p><i data-bind="text: experience"></i></p>
            <p><i data-bind="text: other"></i></p>
        </div>
    </div>

</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/employee_bio.js' %}"></script>
{% endblock %}

rojgar/employee/templates/employee/employee_dashboard.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'employee/css/employee_dashboard.css' %}"/>
<input type="hidden" id="userId" value="{{ user.id }}">
<div class="container-fluid">
    <div class="sidebar">
  <div class="image">
      <img src="{{ user.user_photo.photo.url }}" width="80px" height="80px" class="mx-auto d-block">
      <!--&lt;!&ndash; ko ifnot: photo() &ndash;&gt;-->
            <!--<a href="{% url 'employee:add_profile' %}">Add Profile</a>-->
      <!--&lt;!&ndash; /ko &ndash;&gt;-->
      {% if user.user_photo.photo %}
      <br>
      <a  href="{% url 'employee:update_profile' %}">Update Profile</a>
      {% else %}
      <br>
       <a href="{% url 'employee:add_profile' %}">Add Profile</a>
      {% endif %}
      <b><p class="pt-2">{{ user.username }}</p></b>
      <p>Employee</p>
  </div>
  <a class="nav active" href="{% url 'employee:employee_detail' %}">Detail</a>
  <a class="nav" href="{% url 'employee:employee_service' %}">Service</a>
  <a class="nav" href="{% url 'employee:employee_bio' %}">Bio Data</a>
  <a class="nav" href="{% url 'servicerequest:employee_list_service_request' %}">Request <span class="badge badge-info">New</span></a>
</div>

<div class="content">
{% block employee %}
Employee
{% endblock %}
</div>
</div>

<!--<script src="{% static 'js/jquery.js' %}"></script>-->
<!--<script src="{% static 'js/knockout.js' %}"></script>-->
<!--<script src="{% static 'employee/js/employee.js' %}"></script>-->

{% endblock %}

rojgar/employee/templates/employee/employee_detail.html
{% extends 'employee/employee_dashboard.html' %}
{% block employee %}
<div class="container mt-2">
    <h4 class="bg-info text-white p-2">Your Detail</h4>
    <p><b>Name: </b>{{ user.user_emp.full_name }}</p>
    <p><b>Email: </b>{{ user.user_emp.email }}</p>
    <p><b>Mobile Number:</b>{{ user.user_emp.mobile_number }}</p>
    <p><b>State:</b>{{ user.user_emp.state.name }}</p>
    <p><b>District: </b>{{ user.user_emp.district.name }}</p>
    <p><b>Municipality: </b>{{ user.user_emp.municipality }} </p>
    <p><b>Ward Number: </b> {{ user.user_emp.ward_number }}</p>
    <p><b>Street:</b>{{ user.user_emp.street }}</p>
    <a class="btn btn-primary" href="{% url 'employee:update_employee' %}">Update</a>
</div>

{% endblock %}

rojgar/employee/templates/employee/employee_manage.html
{% extends 'dashboard.html' %}
<title>{% block title %} Employee Manage {% endblock %}</title>

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <a href="{% url 'employee:create_employee' %}" class="btn btn-primary btn-sm">
        <i class="fas fa-plus-circle"></i> Create Employee
      </a>
    </div>
    <div class="col-md-8">
       <h5>Employee List</h5>
    </div>
  </div>
  <hr>
   <table class="table table-striped p-3">
    <thead>
      <tr>
        <th>S.N.</th>
        <th>Name</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>

    </tbody>
  </table>
</div>

{% endblock %}

rojgar/employee/templates/employee/employee_service.html
{% extends 'employee/employee_dashboard.html' %}
{%load static %}
{% block employee %}
<div>
    <a href="{% url 'employee:add_service' %}" class="btn btn-primary m-2">
    Add Service
  </a>
    <div class="table-responsive">
        <input type="hidden"  id="empId" value="{{ user.user_emp.id }}">
    <table class="table table-bordered">
      <thead>
        <tr>
            <th>S.N.</th>
            <th>Service</th>
        </tr>
      </thead>
      <tbody>
      <!-- ko foreach: empService -->
        <tr>
            <td data-bind="text: $index()+1"></td>
            <td data-bind="text: service_name"></td>
        </tr>
      <!-- /ko -->
      </tbody>
    </table>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/employee_service.js' %}"></script>

{% endblock %}

rojgar/employee/templates/employee/signup_form.html
{% extends 'employee_manage.html' %}
<title>{% block title %}Create Employee {% endblock %}</title>

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <div class="card-deck">
              <div class="card">
                <div class="card-body">
                     <h6 class="card-title bg-info text-white p-2">Create New Employee</h6>
                    <form>
                        <div class="form-group">
                            <label for="fullname">Full Name:</label>
                            <input type="text" class="form-control" id="fullname"/>
                        </div>
                        <label>Gender:</label>
                        <div class="form-check">
                          <label class="form-check-label">
                            <input type="radio" class="form-check-input" name="gender">Male
                          </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="gender">Female
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-lable">Other
                                <input type="radio" class="form-check-input" name="gender">
                            </label>
                        </div>

                        <div class="form-group">
                            <label for="age"></label>
                            <input type="number" class="form-check-input" id="age" name="age">Age
                        </div>
                        <div class="form-group">
                            <label for="email">Email address:</label>
                            <input type="email" class="form-control" id="email">
                        </div>
                    </form>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rojgar/employee/templates/employee/update_employee.html
{% extends 'employee/employee_dashboard.html' %}
{% load static %}
{% block employee %}
<div class="container mt-2">
    <div class="row">
        <div class="col-4">
            <form id="employee_update_form" data-s-url="{% url 'address:load_state' %}"
                  data-d-url="{% url 'address:load_district' %}"
                  data-m-url="{% url 'address:load_municipality' %}"

            >
                <input type="hidden" id="empId" value="{{ user.user_emp.id }}">
                <div class="form-group">
                    <label for="fullname">Full Name *</label>
                    <input type="text" class="form-control" data-bind="value: fullName" id="fullname"/>
                </div>
                <div class="form-group">
                    <label for="fullname">Email *</label>
                    <input type="text" class="form-control" data-bind="value: email" id="email"/>
                </div>
                <div class="form-group">
                    <label for="fullname">Mobile Number *</label>
                    <input type="text" class="form-control" data-bind="value: mobileNumber" id="mobile"/>
                </div>
                <label>State *</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa-map-marker"></i></span>
                    </div>
                    <select class="form-control" data-bind="options: stateList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedState,
                                 optionsCaption: 'Choose State...' "></select>

                </div>

                <label>District *</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa-map-marker"></i></span>
                    </div>
                    <select class="form-control" data-bind="options: districtList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedDistrict,
                                 optionsCaption: 'Choose District...' "></select>

                </div>

                <label>Municipality *</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa-map-marker"></i></span>
                    </div>

                    <select class="form-control" data-bind="options: municipalityList, optionsText: 'name',
                                 optionsValue: 'id', value: selectedMunicipality,
                                 optionsCaption: 'Choose Municipality...' "></select>
                </div>

                <div class="form-group">
                    <label for="fullname">Ward Number</label>
                    <input type="text" class="form-control" data-bind="value: wardNumber" id="ward_no"/>
                </div>
                <div class="form-group">
                    <label for="fullname">Street</label>
                    <input type="text" class="form-control" data-bind="value: street" id="street"/>
                </div>
                <a class="btn btn-success" href="#">Save</a>
            </form>
        </div>
    </div>

</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/update_employee.js' %}"></script>
{% endblock %}

rojgar/employee/templates/employee/update_profile.html
{% extends 'employee/employee_dashboard.html' %}
{%load static %}
{% block employee %}
<div>
    <div class="col-md-6 m-2">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">

                <h4 class="modal-title">Update Profile</h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form id="update-profile-form">
                    <input type="hidden"  id="user" value="{{ user.id }}">
                    <div class="form-group">
                        <label>Profile</label>
                        <input  id="image" type="file"  class="form-control" >
                    </div>
                </form>
            </div>
            <input type="hidden" id="empID" value="{{ user.user_emp.id }}"/>
            <!-- Modal footer -->
            <div class="modal-footer">

                <button class="btn btn-success" data-bind="click: save">Save</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'employee/js/update_profile.js' %}"></script>
{% endblock %}