rojgar/dashboard/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('admin', DashBoardView.as_view(), name='admin_dashboard'),

]

rojgar/job/api/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('api/create_job', CreateJobAPIView.as_view(), name='create_job'),
    path('api/create_category', CreateJobCategoryAPIView.as_view(), name='create_category'),
    path('api/list_category', ListJobCategoryAPIView.as_view(), name='list_category'),
    path('api/list_job', ListJobAPIView.as_view(), name='list_job'),
    path('api/update_category', UpdateJobCategoryAPIView.as_view(), name='update_category'),
    path('api/update_job', UpdateJobAPIView.as_view(), name='update_job')
]

rojgar/job/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('manage-job/', ManageJobView.as_view(), name='manage_job'),
    path('manage-category/', ManageCategoryView.as_view(), name='manage_category'),
    path('create-job/', CreateJobView.as_view(), name='create_job'),
    path('create-category/', CreateCategoryView.as_view(), name='create_category'),
    path('update-job', UpdateJobView.as_view(), name='update_job'),
]

rojgar/rojgar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/job/', include(('job.urls','job'), namespace='job')),
    path('api/job/', include(('job.api_urls', 'job'), namespace='job_api')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('api/user/', include(('user.api_urls', 'user'), namespace='user_api')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('api/home/', include(('home.api_urls', 'home'), namespace='home_api')),
    path('employee/', include(('employee.urls', 'employee'), namespace='employee')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('address/', include(('address.urls', 'address'), namespace='address')),
    path('api/employee/', include(('employee.api_urls','employee'), namespace='employee_api')),
    path('servicerequest/', include(('servicerequest.urls', 'servicerequest'), namespace='servicerequest')),
    path('api/servicerequest/', include(('servicerequest.api_urls','servicerequest'), namespace='servicerequest_api')),

]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rojgar/job/models.py
from django.db import models
from mptt.models import TreeForeignKey,MPTTModel
# Create your models here.
class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return f'{self.name}'


class Job(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, related_name='job_category')
    description = models.TextField()
    image = models.FileField(upload_to='media', null=True, blank=True)

    def __str__(self):
        return f'{self.category}|{self.name}'

rojgar/job/api/views.py
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework import status
from ..serializer.serializers import *
from rest_framework.parsers import FileUploadParser,MultiPartParser,JSONParser,FormParser
from ..category_tree import root_category

class CreateJobCategoryAPIView(APIView):

    def post(self, request):
        data = request.data
        serializer = JobCategorySerializer(data = data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Saved."})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CreateJobAPIView(APIView):

    parser_classes = (MultiPartParser, FormParser)
    def post(self, request):
        data = request.data
        print(data)
        serializer = JobSerializer(data=data)
        print (serializer)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Saved."})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ListJobCategoryAPIView(ListAPIView):

    serializer_class = JobCategorySerializer
    queryset = Category.objects.all()


class ListJobAPIView(ListAPIView):

    serializer_class = JobSerializer
    queryset = Job.objects.all()



class UpdateJobCategoryAPIView(APIView):


    def put(self, request):
        data = request.data
        category_id = data['category_id']
        category = Category.objects.get(id=category_id)
        serializer = JobCategorySerializer(instance=category, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Updated."})
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)


class UpdateJobAPIView(APIView):

    parser_classes = (MultiPartParser, FormParser)
    def put(self, request):
        data = request.data
        print(data.get('id'))
        job_id = data.get('id')
        job = Job.objects.get(id=job_id)
        serializer = JobSerializer(instance=job,data=data)
        if serializer.is_valid():
            serializer.save()
            return Response({"response": "Successfully Updated."})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ListCategoryAPIViews(APIView):

    def get(self, request):
        category = root_category()
        serializer = CategorySerializers(category, many=True)
        return Response(serializer.data)


class GetJob(APIView):

    def get(self, request):
        job_id = request.GET.get('job')
        job = Job.objects.get(id=job_id)
        serializer = JobSerializer1(job)
        return Response(serializer.data)

rojgar/job/views.py
from django.shortcuts import render
from django.views import View
from home.decorators import group_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
# Create your views here.

@method_decorator([login_required(login_url='home:home'), group_required('admin')],name='dispatch')
class ManageJobView(View):

    def get(self, request):
        return render(request, 'job/manage_job.html')


@method_decorator([login_required(login_url='home:home'), group_required('admin')],name='dispatch')
class ManageCategoryView(View):

    def get(self, request):
        return render(request, 'job/manage_category.html')


@method_decorator([login_required(login_url='home:home'), group_required('admin')],name='dispatch')
class CreateCategoryView(View):

    def get(self, request):
        return render(request, 'job/category_form.html')


@method_decorator([login_required(login_url='home:home'), group_required('admin')],name='dispatch')
class CreateJobView(View):

    def get(self, request):
        return render(request, 'job/job_forms.html')


@method_decorator([login_required(login_url='home:home'), group_required('admin')],name='dispatch')
class UpdateJobView(View):

    def get(self, request):
        return render(request, 'job/job_forms.html')

rojgar/job/templates/job/category_form.html
{% extends 'job/manage_category.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card-deck">
              <div class="card">
                <div class="card-body">
                     <h6 class="card-title bg-info text-white p-2">Create New Category</h6>
                     <form>

                          <table class="table table-bordered">
                              <thead>
                                <tr>
                                    <th>Parent Category</th>
                                    <th>New Category</th>
                                    <th width="10%">Action</th>
                                </tr>
                              </thead>
                              <tbody>
                            <!-- ko foreach: categoryList -->
                                <tr>
                                   <td>
                                       <select data-bind="options: $root.oldCategoryList,
                                                       optionsText: 'name',
                                                       optionsValue: 'id',
                                                       value: parent,
                                                       optionsCaption: 'Choose Category...'"></select>
                                                       </td>
                                    <td><input type="text" data-bind="value: name" class="form-control"/></td>
                                    <td><button class="btn btn-sm" data-bind="click: $root.removeCategory"><i class="fas fa-trash-alt text-danger"></i></button></td>
                                </tr>
                               <!-- /ko -->
                              </tbody>
                          </table>
                          <button class="btn btn-secondary btn-sm" data-bind="click: addCategory"><i class="fas fa-plus-circle"></i> Add new category</button>
                          <hr>
                         <button class="btn btn-success btn-sm float-right" data-bind="click: saveCategory"><i class="fas fa-save"></i> Save</button>
                     </form>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

 <script src="{% static 'js/jquery.js' %}"></script>
 <script src="{% static 'js/knockout.js' %}"></script>
 <script src="{% static 'job/js/category.js' %}"></script>
{% endblock %}

rojgar/job/templates/job/category_modal_form.html
<!-- The Modal -->
  <div class="modal fade" id="createCategory">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h5 class="modal-title"><i class="fas fa-plus-circle"></i> Create Category</h5>
          <!--<button type="button" class="close" data-dismiss="modal">&times;</button>-->
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <form method="post" data-bind="submit: saveCategory">
              <table class="table table-bordered">
                  <thead>
                    <tr>
                        <th>Parent Category</th>
                        <th>New Category</th>
                        <th width="10%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                <!-- ko foreach: categoryList -->
                    <tr>
                       <td>
                           <select data-bind="options: $root.oldCategoryList,
                                           optionsText: 'name',
                                           optionsValue: 'id',
                                           value: parent,
                                           optionsCaption: 'Choose Category...'"></select>
                                           </td>
                        <td><input type="text" data-bind="value: name" class="form-control"/></td>
                        <td><button class="btn btn-sm" type="submit"><i class="fas fa-trash-alt text-danger"></i></button></td>
                    </tr>
                   <!-- /ko -->
                  </tbody>
              </table>
              <button class="btn btn-secondary btn-sm" data-bind="click: addCategory"><i class="fas fa-plus-circle"></i> Add new category</button>
            </form>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button class="btn btn-success btn-sm" data-bind="click: saveCategory"><i class="fas fa-save"></i> Save</button>
          <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
        </div>

      </div>
    </div>
  </div>

rojgar/job/templates/job/create_job.html
{% load static %}
 <!-- The Modal -->
  <div class="modal fade" id="createJob">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h5 class="modal-title"><i class="fas fa-plus-circle"></i> Create Job</h5>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <form>
              <table class="table table-bordered">
                  <thead>
                    <tr>
                        <th>Category</th>
                        <th>Job Title</th>
                        <th>Photo</th>
                        <th>Description</th>
                        <th width="10%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                <!-- ko foreach: jobList -->
                    <tr>
                       <td><select></select></td>
                        <td><input type="text" class="form-control"/></td>
                        <td><input type="file" class="form-control-file border"/></td>
                        <td><textarea></textarea></td>
                        <td><button class="btn btn-sm" data-bind="click: $root.removeJob"><i class="fas fa-trash-alt text-danger"></i></button></td>
                    </tr>
                   <!-- /ko -->
                  </tbody>
              </table>
              <button class="btn btn-secondary btn-sm" data-bind="click: addJob"><i class="fas fa-plus-circle"></i> Add new job</button>
            </form>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button class="btn btn-success btn-sm"><i class="fas fa-save"></i> Save</button>
          <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
        </div>
        
      </div>
    </div>
  </div>

<script src="{% static 'js/knockout.js' %}"></script>
 <script src="{% static 'job/js/job.js' %}"></script>

rojgar/job/templates/job/file_attachment.html
{% load static %}
<input type="number">
<input type="file" data-bind="fileUpload: uploadFile">
<br/>
<br/>Selected file name: <span data-bind="text: uploadName"></span>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'job/js/file_binding.js' %}"></script>

rojgar/job/templates/job/job_form.html
{% extends 'job/manage_job.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <div class="card-deck">
              <div class="card">
                <div class="card-body">
                     <h6 class="card-title bg-info text-white p-2">Create New Job</h6>
                    <form id="job-form">
                      <table class="table table-bordered">
                          <thead>
                            <tr>
                                <th>Category</th>
                                <th>Job Title</th>
                                <th>Description</th>
                                <th width="10%">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                        <!-- ko foreach: jobList -->
                            <tr>
                               <td>
                                    <select data-bind="options: $root.oldCategoryList,
                                                       optionsText: 'name',
                                                       optionsValue: 'id',
                                                       value: category,
                                                       optionsCaption: 'Choose Category...'">
                               </select></td>
                                <td><input name="title" type="text" data-bind="value: name" class="form-control"/></td>
                                <td><textarea data-bind="value: description"></textarea></td>
                                <td><button class="btn btn-sm" data-bind="click: $root.removeJob"><i class="fas fa-trash-alt text-danger"></i></button></td>
                            </tr>
                           <!-- /ko -->
                          </tbody>
                      </table>
                      <button class="btn btn-secondary btn-sm" data-bind="click: addJob"><i class="fas fa-plus-circle"></i> Add new job</button>
                      <hr>
                        <button class="btn btn-success btn-sm float-right" data-bind="click: saveJob">
                            <i class="fas fa-save"></i> Save</button>
                    </form>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

 <script src="{% static 'js/jquery.js' %}"></script>
 <script src="{% static 'js/knockout.js' %}"></script>
 <script src="{% static 'job/js/job.js' %}"></script>
{% endblock %}

rojgar/job/templates/job/job_forms.html
{% extends 'job/manage_job.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 border p-2">
            <h5 class="bg-info text-white p-2">Job Form</h5>
            <form id="job-form">
                <div class="form-group">
                    <label for="category">Category</label>
                    <select id= "category" class="form-control" data-bind="options: $root.oldCategoryList,
                                                           optionsText: 'name',
                                                           optionsValue: 'id',
                                                           value: selectedCategory,
                                                           optionsCaption: 'Choose Category...'">
                    </select>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Job Title</span>
                    </div>
                    <input type="text" id="jobTitle"  data-bind="value: name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="description">Description:</label>
                    <textarea class="form-control" rows="5" data-bind="value: description" id="description"></textarea>
                </div>
                <div class="form-group">
                    <label for="image">Image:</label>
                     <input type="file" id="image" class="form-control-file border">
                </div>
                <button class="btn btn-success btn-sm float-right" data-bind="click: saveJob">
                    <i class="fas fa-save"></i> Save</button>
                 <button class="btn btn-primary btn-sm float-right mr-3" data-bind="click: saveAndContinue">
                            <i class="fas fa-save"></i> Save and continue</button>
            </form>
        </div>
    </div>
</div>

 <script src="{% static 'js/jquery.js' %}"></script>
 <script src="{% static 'js/knockout.js' %}"></script>
 <script src="{% static 'job/js/job.js' %}"></script>
{% endblock %}

rojgar/job/templates/job/manage_category.html
{% extends 'dashboard/admin_dashboard.html' %}
{% load static %}
<title>{% block title %} Manage-Job {% endblock %}</title>
{% block breadcrum %}
<a href="{% url 'dashboard:admin_dashboard' %}">{{ block.super }}</a> / <a href="#">Manage Category</a>
{% endblock %}
{% block content %}
<style>
        .cate{
            font-size: 16px;
            font-weight: bold;
           }

</style>
<link rel="stylesheet" href="{% static 'job/css/treetable.css' %}">
<link rel="stylesheet" href="{% static 'job/css/treetable.theme.default.css' %}">
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <!-- Button to Open job category form -->
            <!--<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createCategory">-->
            <a class="btn btn-primary btn-sm" href="{% url 'job:create_category' %}">
                <i class="fas fa-plus-circle"></i> Create Category
            </a>
        </div>
        <div class="col-md-8">
            <h5>Category List</h5>
        </div>
    </div>
    <hr>
    <a href="#" onclick="jQuery('.advance').treetable('expandAll'); return false;">Expand all</a> |
    <a href="#" onclick="jQuery('.advance').treetable('collapseAll'); return false;">Collapse all</a>
    <table border="1" class="advance" id="mytable">
        <thead>
        <tr>
            <th>Category</th>
            <th>Job</th>
        </tr>
        </thead>
        <tbody data-bind="template: { name: 'category_template', foreach: category }">

        </tbody>
    </table>

    <script type="text/html" id="category_template">
        <tr data-bind="attr: { 'data-tt-id' : id , 'data-tt-parent-id': parent }, css: { cate: parent == null}">
            <td><a data-bind="click: $parent.updateCategory,text: name"></a></td>
            <td>--</td>

        </tr>
        <!-- ko foreach: job_list -->
        <!-- ko template: 'job_template' -->
        <!-- /ko -->
        <!-- /ko -->

        <!-- ko foreach: category_list -->
        <!-- ko template: 'category_template' -->
        <!-- /ko -->
        <!-- /ko -->

    </script>
    <script type="text/html" id="job_template">
        <tr style=" color: blue;" data-bind="attr: { 'data-tt-id': id+'a', 'data-tt-parent-id': category }">
            <td></td>
            <td><a href="#" data-bind="text: name"></a></td>
        </tr>
    </script>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'job/js/treetable.js' %}"></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'job/js/category_list.js' %}"></script>
<script>
     $("#mytable").treetable({ expandable: true });
     $(".advance").treetable({ expandable: true });
</script>
{% endblock %}

rojgar/job/templates/job/manage_job.html
{% extends 'dashboard/admin_dashboard.html' %}
{% load static %}
<title>{% block title %} Manage-Job {% endblock %}</title>
{% block breadcrum %}
<a href="{% url 'dashboard:admin_dashboard' %}">{{ block.super }}</a> / <a href="#">Manage Job</a>
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>



<div class="container">
  <div class="row">
    <div class="col-md-4">
      <a href="{% url 'job:create_job' %}" class="btn btn-primary btn-sm">
        <i class="fas fa-plus-circle"></i> Create Job
      </a>

    </div>
    <div class="col-md-8">
       <h5>Job List</h5>
    </div>
  </div>
  <hr>
   <table id="job-table" class="display" width="100%">
       <thead>
       <tr>
           <th>S.N.</th>
           <th>Job Title</th>
           <th>Category</th>
           <th>Description</th>
           <th>Image</th>
           <th>Action</th>
       </tr>
       </thead>
    <tbody>
   <!-- ko foreach: jobList -->
    <tr>
        <td data-bind="text: $index()+1"></td>
        <td data-bind="text: name"></td>
        <td data-bind="text: category"></td>
        <td data-bind="text: description"></td>
        <td> <img data-bind="attr: { src: image }" width="50px"/></td>
        <td><a class="btn btn-primary btn-sm text-white" data-bind="click: $root.updateJob">Update</a> </td>
    </tr>
       <!-- /ko -->
    </tbody>
   </table>

</div>

<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" defer></script>
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'job/js/list_job.js' %}"></script>
{% endblock %}